/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Verifica a conexão real com o Postgres, não só se o processo está de pé.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Saudável. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example ok */
                            status?: string;
                        };
                    };
                };
                /** @description Dependência (Postgres) indisponível. */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example indisponível */
                            status?: string;
                            error?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Métricas Prometheus
         * @description Formato de exposição do Prometheus (text/plain). Sem autenticação por convenção do ecossistema — restrinja o acesso por rede em produção.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Métricas no formato Prometheus. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dados do usuário autenticado
         * @description Confirma que o token foi validado e o usuário foi resolvido/provisionado (JIT) com sucesso.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** Format: uuid */
                            id?: string;
                            nome?: string;
                            /** Format: email */
                            email?: string;
                            is_fiscal?: boolean;
                            is_admin?: boolean;
                        };
                    };
                };
                401: components["responses"]["NaoAutenticado"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/kanban/etapas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista as 6 etapas fixas do funil */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["KanbanEtapa"][];
                    };
                };
                401: components["responses"]["NaoAutenticado"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/kanban/tipos-documento": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista o catálogo de tipos de documento */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["TipoDocumento"][];
                    };
                };
                401: components["responses"]["NaoAutenticado"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/radar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista os itens em risco (Radar de Alertas)
         * @description Varre contratos e processos ativos e retorna todo item que entra em algum dos 3 sinais de alerta: vigência de contrato perto do fim, certidão vencida/vencendo anexada a um processo em andamento, ou processo parado na mesma etapa do Kanban há muito tempo. Sem paginação — a lista é o conjunto completo de itens em risco.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ItemRadar"][];
                    };
                };
                401: components["responses"]["NaoAutenticado"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contratos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista contratos (paginado) */
        get: {
            parameters: {
                query?: {
                    pagina?: components["parameters"]["Pagina"];
                    tamanho?: components["parameters"]["Tamanho"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ResultadoPaginado"] & {
                            dados?: components["schemas"]["Contrato"][];
                        };
                    };
                };
                401: components["responses"]["NaoAutenticado"];
            };
        };
        put?: never;
        /**
         * Cadastra um novo contrato
         * @description Restrito a fiscais habilitados (`IsFiscal=true`). Sujeito a rate limit.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["NovoContratoRequest"];
                };
            };
            responses: {
                /** @description Criado. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Contrato"];
                    };
                };
                400: components["responses"]["RequisicaoInvalida"];
                401: components["responses"]["NaoAutenticado"];
                403: components["responses"]["Proibido"];
                429: components["responses"]["MuitasRequisicoes"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contratos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ContratoId"];
            };
            cookie?: never;
        };
        /** Busca um contrato por ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ContratoId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Contrato"];
                    };
                };
                400: components["responses"]["RequisicaoInvalida"];
                401: components["responses"]["NaoAutenticado"];
                404: components["responses"]["NaoEncontrado"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Atualiza campos editáveis do contrato
         * @description Só os campos presentes no corpo são alterados. `numero_contrato`, `fiscal_id` e `tipo_objeto` não são editáveis por aqui (identidade e classificação do contrato).
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ContratoId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AtualizarContratoRequest"];
                };
            };
            responses: {
                /** @description OK. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Contrato"];
                    };
                };
                400: components["responses"]["RequisicaoInvalida"];
                401: components["responses"]["NaoAutenticado"];
                403: components["responses"]["Proibido"];
                404: components["responses"]["NaoEncontrado"];
                429: components["responses"]["MuitasRequisicoes"];
            };
        };
        trace?: never;
    };
    "/api/v1/contratos/{id}/encerrar": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ContratoId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Encerra o contrato (soft-close)
         * @description Marca `Ativo=false`. Contrato encerrado não aceita novos `POST /processos`, mas o histórico continua consultável. Não há reversão automática.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ContratoId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Contrato"];
                    };
                };
                401: components["responses"]["NaoAutenticado"];
                403: components["responses"]["Proibido"];
                404: components["responses"]["NaoEncontrado"];
                429: components["responses"]["MuitasRequisicoes"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/processos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista processos de uma etapa do Kanban (paginado)
         * @description O parâmetro `etapa` é obrigatório — o board sempre navega por coluna.
         */
        get: {
            parameters: {
                query: {
                    /** @description ID da etapa do Kanban (1 a 6). */
                    etapa: number;
                    pagina?: components["parameters"]["Pagina"];
                    tamanho?: components["parameters"]["Tamanho"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ResultadoPaginado"] & {
                            dados?: components["schemas"]["ProcessoPagamento"][];
                        };
                    };
                };
                400: components["responses"]["RequisicaoInvalida"];
                401: components["responses"]["NaoAutenticado"];
            };
        };
        put?: never;
        /**
         * Abre um novo processo de pagamento (card)
         * @description Sempre entra na Etapa 1. Rejeitado com 400 se o contrato estiver encerrado (`Ativo=false`).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** Format: uuid */
                        contrato_id: string;
                        /**
                         * @description Formato "MM/AAAA".
                         * @example 07/2026
                         */
                        mes_referencia: string;
                    };
                };
            };
            responses: {
                /** @description Criado. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProcessoPagamento"];
                    };
                };
                400: components["responses"]["RequisicaoInvalida"];
                401: components["responses"]["NaoAutenticado"];
                403: components["responses"]["Proibido"];
                404: components["responses"]["NaoEncontrado"];
                429: components["responses"]["MuitasRequisicoes"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/processos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ProcessoId"];
            };
            cookie?: never;
        };
        /** Busca um processo por ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ProcessoId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProcessoPagamento"];
                    };
                };
                400: components["responses"]["RequisicaoInvalida"];
                401: components["responses"]["NaoAutenticado"];
                404: components["responses"]["NaoEncontrado"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/processos/{id}/avancar": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ProcessoId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Avança o processo para a próxima etapa
         * @description Só avança se o checklist da etapa atual estiver completo (Seção 5 da documentação de domínio). Ao confirmar a Etapa 3, dispara em background o envio do pacote digital à empresa contratada.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ProcessoId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Avançou. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProcessoPagamento"];
                    };
                };
                400: components["responses"]["RequisicaoInvalida"];
                401: components["responses"]["NaoAutenticado"];
                403: components["responses"]["Proibido"];
                404: components["responses"]["NaoEncontrado"];
                422: components["responses"]["ChecklistIncompleto"];
                429: components["responses"]["MuitasRequisicoes"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/processos/{id}/concluir": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ProcessoId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Marca o processo como pago
         * @description Só permitido a partir da etapa final (6 — Contabilidade).
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ProcessoId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Concluído. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProcessoPagamento"];
                    };
                };
                400: components["responses"]["RequisicaoInvalida"];
                401: components["responses"]["NaoAutenticado"];
                403: components["responses"]["Proibido"];
                404: components["responses"]["NaoEncontrado"];
                429: components["responses"]["MuitasRequisicoes"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/processos/{id}/documentos": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ProcessoId"];
            };
            cookie?: never;
        };
        /** Lista os documentos anexados ao processo */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ProcessoId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DocumentoAnexo"][];
                    };
                };
                401: components["responses"]["NaoAutenticado"];
            };
        };
        put?: never;
        /**
         * Anexa um documento ao processo
         * @description multipart/form-data. Se o SHA-256 do conteúdo já existir para este processo, reaproveita o registro existente em vez de duplicar (não cria um novo). Limite de 20MB por arquivo.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ProcessoId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        /** @description ID de um tipo em GET /kanban/tipos-documento. */
                        tipo_documento_id: number;
                        /** Format: binary */
                        arquivo: string;
                        /**
                         * Format: date
                         * @description Opcional. Formato "AAAA-MM-DD" — só faz sentido pra tipos com ExigeValidade=true (certidões). Alimenta o Radar de Alertas.
                         */
                        data_validade?: string;
                    };
                };
            };
            responses: {
                /** @description Anexado. */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["DocumentoAnexo"];
                    };
                };
                400: components["responses"]["RequisicaoInvalida"];
                401: components["responses"]["NaoAutenticado"];
                403: components["responses"]["Proibido"];
                404: components["responses"]["NaoEncontrado"];
                /** @description Arquivo excede 20MB. */
                413: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ErroSimples"];
                    };
                };
                429: components["responses"]["MuitasRequisicoes"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/processos/{id}/relatorio": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ProcessoId"];
            };
            cookie?: never;
        };
        /**
         * Gera o Relatório de Pagamento (PDF)
         * @description PDF pronto para impressão/assinatura física. Layout funcional próprio do Selene, não o modelo oficial da prefeitura (nenhum template real foi fornecido — ver README, seção "Limitações").
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: components["parameters"]["ProcessoId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description PDF gerado. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/pdf": string;
                    };
                };
                400: components["responses"]["RequisicaoInvalida"];
                401: components["responses"]["NaoAutenticado"];
                404: components["responses"]["NaoEncontrado"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Lista todos os usuários
         * @description Restrito a administradores (`IsAdmin=true`).
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Usuario"][];
                    };
                };
                401: components["responses"]["NaoAutenticado"];
                403: components["responses"]["Proibido"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /** Busca um usuário por ID */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Usuario"];
                    };
                };
                400: components["responses"]["RequisicaoInvalida"];
                401: components["responses"]["NaoAutenticado"];
                403: components["responses"]["Proibido"];
                404: components["responses"]["NaoEncontrado"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Altera permissões/matrícula de um usuário
         * @description Só os campos presentes no corpo são alterados.
         */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        is_fiscal?: boolean;
                        is_admin?: boolean;
                        matricula?: string;
                    };
                };
            };
            responses: {
                /** @description OK. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Usuario"];
                    };
                };
                400: components["responses"]["RequisicaoInvalida"];
                401: components["responses"]["NaoAutenticado"];
                403: components["responses"]["Proibido"];
                404: components["responses"]["NaoEncontrado"];
            };
        };
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErroSimples: {
            error?: string;
        };
        ResultadoPaginado: {
            /** @example 42 */
            total?: number;
            /** @example 1 */
            pagina?: number;
            /** @example 20 */
            tamanho_pagina?: number;
        };
        KanbanEtapa: {
            /** @example 1 */
            ID?: number;
            /** @example Elaborar OF / Pré-Empenho */
            Nome?: string;
            /** @example 1 */
            Posicao?: number;
        };
        TipoDocumento: {
            /** @example 4 */
            ID?: number;
            /** @example Nota de Empenho */
            Nome?: string;
            /** @description true = tipo que vence (certidões) — o upload aceita 'data_validade'. */
            ExigeValidade?: boolean;
        };
        /** @description Um alerta individual do Radar (Fase 1 do roadmap). */
        ItemRadar: {
            /** @enum {string} */
            tipo?: "vigencia_contrato" | "certidao" | "processo_parado";
            /** @enum {string} */
            nivel?: "ATENCAO" | "CRITICO";
            /** Format: uuid */
            contrato_id?: string;
            /** @example 125/2026 */
            numero_contrato?: string;
            /**
             * Format: uuid
             * @description Ausente pra alertas de tipo vigencia_contrato (o alerta é do contrato, não de um processo específico).
             */
            processo_id?: string | null;
            /** @example Faltam 25 dias para o fim da vigência do contrato */
            mensagem?: string;
            /** @description Negativo quando o prazo já passou (vencido/parado há N dias). */
            dias_restantes?: number;
        };
        /** @description KeycloakID (claim "sub" do token OIDC) é omitido de propósito — nunca serializado (json:"-"), identificador interno sem uso na UI. */
        Usuario: {
            /** Format: uuid */
            ID?: string;
            Nome?: string;
            /** Format: email */
            Email?: string;
            IsFiscal?: boolean;
            IsAdmin?: boolean;
            Matricula?: string;
            /** Format: date-time */
            CriadoEm?: string;
            /** Format: date-time */
            AtualizadoEm?: string;
        };
        Contrato: {
            /** Format: uuid */
            ID?: string;
            /** @example 125/2026 */
            NumeroContrato?: string;
            PortariaNomeacao?: string;
            /** Format: date */
            DataAssinatura?: string;
            ContratadaNome?: string;
            ContratadaCNPJ?: string;
            /** Format: email */
            ContratadaEmail?: string;
            /** Format: uuid */
            FiscalID?: string;
            Fiscal?: components["schemas"]["Usuario"];
            /** @enum {string} */
            TipoObjeto?: "CONSUMO" | "PERMANENTE" | "SERVICO";
            /** @description false = contrato encerrado (soft-close). */
            Ativo?: boolean;
            /**
             * Format: date
             * @description Alimenta o Radar de Alertas — null se não cadastrada.
             */
            DataVigenciaFim?: string | null;
            /** Format: date-time */
            CreatedAt?: string;
            /** Format: date-time */
            UpdatedAt?: string;
        };
        NovoContratoRequest: {
            /** @example 125/2026 */
            numero_contrato: string;
            portaria_nomeacao?: string;
            /**
             * @description Formato "AAAA-MM-DD".
             * @example 2026-01-15
             */
            data_assinatura: string;
            contratada_nome: string;
            contratada_cnpj: string;
            /** Format: email */
            contratada_email?: string;
            /**
             * Format: uuid
             * @description Precisa ser um usuário com IsFiscal=true.
             */
            fiscal_id: string;
            /** @enum {string} */
            tipo_objeto: "CONSUMO" | "PERMANENTE" | "SERVICO";
            /**
             * Format: date
             * @description Opcional. Formato "AAAA-MM-DD" — alimenta o Radar de Alertas.
             */
            data_vigencia_fim?: string;
        };
        AtualizarContratoRequest: {
            portaria_nomeacao?: string;
            contratada_nome?: string;
            contratada_cnpj?: string;
            /** Format: email */
            contratada_email?: string;
            /**
             * Format: date
             * @description Formato "AAAA-MM-DD". Enviar string vazia limpa a vigência cadastrada.
             */
            data_vigencia_fim?: string;
        };
        ProcessoPagamento: {
            /** Format: uuid */
            ID?: string;
            /** Format: uuid */
            ContratoID?: string;
            Contrato?: components["schemas"]["Contrato"];
            /** @example 07/2026 */
            MesReferencia?: string;
            EtapaAtualID?: number;
            EtapaAtual?: components["schemas"]["KanbanEtapa"];
            /** @enum {string} */
            Status?: "Ativo" | "Concluido";
            /** Format: date-time */
            CreatedAt?: string;
            /** Format: date-time */
            UpdatedAt?: string;
        };
        /** @description CaminhoStorage (path local no servidor) é omitido de propósito — nunca serializado (json:"-"). */
        DocumentoAnexo: {
            /** Format: uuid */
            ID?: string;
            /** Format: uuid */
            ProcessoPagamentoID?: string;
            TipoDocumentoID?: number;
            TipoDocumento?: components["schemas"]["TipoDocumento"];
            /** @description Sanitizado no upload (sem componentes de caminho ou caracteres de controle). */
            NomeArquivo?: string;
            /** @description SHA-256 (hex) do conteúdo. */
            HashArquivo?: string;
            /** Format: uuid */
            EnviadoPorID?: string;
            EnviadoPor?: components["schemas"]["Usuario"];
            /** Format: date-time */
            DataUpload?: string;
            /**
             * Format: date
             * @description Só preenchida pra tipos com ExigeValidade=true (certidões).
             */
            DataValidade?: string | null;
        };
    };
    responses: {
        /** @description Token ausente, inválido, expirado, ou issuer/audience não batem. */
        NaoAutenticado: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErroSimples"];
            };
        };
        /** @description Usuário autenticado, mas sem a permissão exigida (IsFiscal/IsAdmin). */
        Proibido: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErroSimples"];
            };
        };
        /** @description Recurso não encontrado. */
        NaoEncontrado: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErroSimples"];
            };
        };
        /** @description Corpo/parâmetros inválidos, ou regra de negócio violada (ex: contrato encerrado). */
        RequisicaoInvalida: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErroSimples"];
            };
        };
        /** @description Rate limit excedido para este usuário (rotas de escrita). */
        MuitasRequisicoes: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErroSimples"];
            };
        };
        /** @description O checklist obrigatório da etapa atual ainda não está completo. */
        ChecklistIncompleto: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @example checklist incompleto */
                    error?: string;
                    /**
                     * @example [
                     *       "Nota Fiscal / Fatura",
                     *       "Ordem de Recepção"
                     *     ]
                     */
                    documentos_pendentes?: string[];
                };
            };
        };
    };
    parameters: {
        ContratoId: string;
        ProcessoId: string;
        Pagina: number;
        Tamanho: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
